### PR TITLE
mention two more CodeRefinery lessons on Git

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by orchid00** [comment]
Thanks @bast and @coderefinery 👍

**Comment by bast** [comment]
Thanks for merging and listing these! Thanks for this useful list!

**Comment by orchid00** [comment]
Thanks @bast I've just added a theme :)

**Comment by bast** [comment]
Looks great!

Sorry for changing topic but one problem of this repository being a fork but at the same time quite different from the forked repo is that it does not have any issue tracking. I wanted to open an issue for this repo. Could you please either add an issue tracker or consider cutting the fork relation?

**Comment by orchid00** [comment]
Yeah I thought of that @bast. How do I cut the relationship? Should I import it from myself? Or should I keep my local copy, delete the report and create a new, then upload all contents again?. I'm not sure if this is the best way @matkuzak do you know?

**Comment by bast** [comment]
Options:
- You can add issue tracking if a forking relation makes sense in future
- I think forking relation can only be cut by GitHub support
- You could rename this repo for backup, create an empty one and clone+push to it, later remove the backup

**Comment by orchid00** [comment]
@bast Got new site same name as before, and can collect issues

**Pull request merged**
